# Generated by Django 5.2.14 on 2026-05-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('text_preview', models.CharField(max_length=240)),
                ('text_length', models.PositiveIntegerField()),
                ('label', models.PositiveSmallIntegerField()),
                ('fake_probability', models.FloatField()),
                ('real_probability', models.FloatField()),
                ('threshold', models.FloatField()),
                ('source', models.CharField(default='web', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
